In [1]:
# importing pytorch

import torch
torch.__version__

'2.12.0+cpu'

### Scalar,Vector,Matrix,Tensor

In [2]:
# creating scalar using tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
print(scalar.ndim)
print(scalar.item()) #only works with one-element tensors
print(scalar.shape)

0
7
torch.Size([])


In [4]:
# vector
vector = torch.tensor([7, 8, 9, 10])
vector

tensor([ 7,  8,  9, 10])

In [5]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([4])


In [6]:
# Matrix
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


In [8]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [9]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


### Random Tensors

In [10]:
# randomize tensors
# Create a random tensor of size (2, 3)
random_tensor = torch.rand(size=(2, 3))
random_tensor, random_tensor.dtype

(tensor([[0.1810, 0.0834, 0.5071],
         [0.3995, 0.1490, 0.3688]]),
 torch.float32)

In [11]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Create a tensor of only zeros and ones

In [12]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [13]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [14]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [16]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([2.0, 4.0, 6.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [17]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

### Getting information out of tensors

In [18]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7039, 0.2029, 0.7839, 0.6253],
        [0.5965, 0.8386, 0.7902, 0.4812],
        [0.7741, 0.7895, 0.7187, 0.8704]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensor Operations

In [19]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [20]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [21]:
tensor

tensor([1, 2, 3])

In [22]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [23]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([-90, -80, -70])

In [24]:
tensor

tensor([-9, -8, -7])

In [25]:
tensor = tensor + 10
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)
print("Equals:", torch.multiply(tensor, tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Equals: tensor([1, 4, 9])


In [26]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.
tensor = torch.tensor([1, 2, 3])

# Element-wise matrix multiplication
print(tensor * tensor)

# Matrix multiplication
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9])
tensor(14)


In [27]:
# # Shapes need to be in the right way  
# tensor_A = torch.tensor([[1, 2],
#                          [3, 4],
#                          [5, 6]], dtype=torch.float32)

# tensor_B = torch.tensor([[7, 10],
#                          [8, 11], 
#                          [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

In [28]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

NameError: name 'tensor_A' is not defined

In [29]:
x = torch.arange(0, 100, 10)
print(x)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [30]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [31]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

torch.float32


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [32]:
# Create a tensor
import torch
x = torch.arange(1., 9.)
print(x, x.shape)

# Add an extra dimension
x_reshaped = x.reshape(1, 8) # try other shapes, it will produce an error.
x_reshaped, x_reshaped.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [33]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [34]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 8)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [35]:
z = x.view(2,4)
z, z.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [36]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [37]:
x = torch.arange(6)

a = x.view(2, 3)
b = x.reshape(2, 3)

a[0, 0] = 100
print(x)

tensor([100,   1,   2,   3,   4,   5])


In [38]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) 
x_stacked

tensor([[100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5]])

In [39]:
# Stacking using dim=1
x_stacked = torch.stack([x, x, x, x], dim=1) 
x_stacked

tensor([[100, 100, 100, 100],
        [  1,   1,   1,   1],
        [  2,   2,   2,   2],
        [  3,   3,   3,   3],
        [  4,   4,   4,   4],
        [  5,   5,   5,   5]])

In [40]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


In [41]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.shape)

y = x.permute(1, 0)

print(y)
print(y.shape)

torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


### Indexing

In [42]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [43]:
print(x[:, 0]) # Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, :, 1])# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, 1, 1]) # Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[0, 0, :]) # same as x[0][0]

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


### Pytorch Tensor to NumPy arrays and vice versa

In [44]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [45]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Tensors on GPU


In [46]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [47]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [48]:
# Count number of devices
torch.cuda.device_count()

0

In [49]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [50]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### Discussion and Conclusion


This lab introduced core PyTorch tensor operations like creation,data types,arithmetic,matrix multiplication,reshaping,indexing, NumPy interoperability, and GPU placement. A key insight was that inner dimensions must align for torch.matmul, and that operations like view share memory with the original tensor,so changes propagate back.

The lab built a practical foundation in tensor manipulation that underpins all PyTorch model development.Mastering these primitives ie shapes,dtypes,devices and operations is essential before moving on to building and training neural networks.